graph LR
    A
    B-->behavior
    C-->coincidence
    C-->comic
    C-->concentrate
    C-->conclude
    C-->critical
    D-->destination
    D-->devastate
    D-->devastating
    D-->disaster
    E-->exclusively
    E-->explore
    F-->fantastic
    F-->firm
    I-->identical
    I-->illusion
        illusion-->illusion_1>illusion and reality]
    I-->implement
    I-->innovative
    I-->insect
    I-->insight
    I-->intrigue
    I-->invest
    M-->management
    M-->mortality
    N-->numerous
    O-->overlook
    P-->pest
    P-->poartial
    P-->procedure
    P-->pursue
    Q-->quota
    R-->reveal
    R-->rhythm
    S-->sensation
    S-->stream
    S-->Stroke
    S-->sustainable
    T-->transport
    T-->trigger


