graph LR
    A
    B-->behavior
    C-->comic
    C-->concentrate
    C-->critical
    D-->destination
    D-->devastate
    D-->devastating
    E
    F-->fantastic
    F-->firm
    I-->innovative
    I-->intrigue
    M--management
    P-->poartial
    P-->pursue
    R-->rhythm
    S-->stream
    T-->transport


