graph LR
    A
    B-->behavior
    C-->coincidence
    C-->comic
    C-->concentrate
    C-->critical
    D-->destination
    D-->devastate
    D-->devastating
    D-->disaster
    E
    F-->fantastic
    F-->firm
    I-->identical
    I-->illusion
        illusion-->illusion_1>illusion and reality]
    I-->innovative
    I-->insect
    I-->intrigue
    M-->management
    M-->mortality
    N-->numerous
    P-->pest
    P-->poartial
    P-->pursue
    R-->rhythm
    S-->sensation
    S-->stream
    S-->Stroke
    S-->sustainable
    T-->transport
    T-->trigger


